lib/HTML/FormHandler/Validate.pm
t/validation/types.t

Update HTML::FormHandler::Validate to detect and use subclasses of Type::Tiny constraints, such as Type::Tiny::Class or Type::Tiny::Enum

Validation

---

lib/HTML/FormHandler/Field/Integer.pm

This is an opinionated change proposal.
According to a designer I've been working with, and backed up by discussion found around the web (e.g. [on Stack Overflow](http://stackoverflow.com/questions/8216278/html5-input-type-number-vs-tel) and [http://mobileinputtypes.com](http://mobileinputtypes.com)), `tel` is a more practically effective HTML5 input type when dealing with fields meant to only accept digits, versus `number`. This is especially true on mobile, where `tel` presents the user with a telephone-style keypad, and `number` doesn't. (On iOS, for instance, `number` pops up the usual system alpha-numeric keyboard.)

Changing the HTML5 tag-text of Integer fields to "tel".

---

lib/HTML/FormHandler/Field/Date.pm
t/fields/dates.t

The HTML5 "date" field type always and only formats its date in ISO format (YYYY-MM-DD). I have therefore added a restriction to the Date field class such that, if its parent form has its is_html5 flag set, _and_ its format attribute is anything other than ISO, then it dies with an appropriate complaint.
I have also updated the POD and tests appropriately.
Finding the right place to put the new validation code was an interesting challenge. I decided that  rendering-time was the right time to check, and `get_tag` seemed as good a method to wrap the validator around as any (since straight-up modifying `render` doesn't seem to be an option?)

Adding HTML5 format restrictions for Date fields

---

lib/HTML/FormHandler/Field/Date.pm

Subclass may be using different input type (eg. to avoid UI confusion with using a datepicker widget).
Signed-off-by: Charlie Garrison <cngarrison@gmail.com>

Don't warn about date format unless set to `date`

---

lib/HTML/FormHandler/Widget/Field/CheckboxGroup.pm
t/bootstrap3/controls.t

My CheckboxGroup's labels were all bold
That's because it hadn't been wrapped in `<div class="checkbox">`
Now it is

Wrap checkbox in CheckboxGroup, if requested

---

lib/HTML/FormHandler/Field/Text.pm
t/validation/types.t

Before this change, submitting a form with parameters like
"?field=value1&field=value2" resulted in setting a Text field to
something like ARRAY(0x...).  Now, the field fails validation.

Ensure Text fields only contain a single value

---

README.md

It comprises just some information from the PODs and states  that it needs Dist::Zilla to build the distribution
Signed-off-by: Jose Luis Perez Diez <jluis@escomposlinux.org>

Add a README.md file

---

lib/HTML/FormHandler/Field/Select.pm
t/fields/select.t

This makes options defined by subroutines behave consistently with those defined otherwise by the changes in 021fd3b.

Support arrayref-of-arrayref options ins a subroutine

---

lib/HTML/FormHandler/Field/Money.pm
t/fields/fields.t

Default behavior is the same as the existing module. Although the order in which the number is validated and converted has been switched so that the input is validated before the conversion is attempted. This made more sense when the additional conversion steps where added.

Add comma digit grouping and custom currency symbol

---

lib/HTML/FormHandler/Field/Select.pm

I couldn't find any documentation of options_ref.
I got stuck trying to do: https://gist.github.com/Edward-Francis/0e3eece45f03eaa5fa63691dddcc9439

Document options_ref() usage with Template Toolkit

---

lib/HTML/FormHandler/Field/Repeatable.pm

This was mentioned in the synopsis but not in the actual ATTRIBUTES section

Add init_contains to Repeatable doc

---

lib/HTML/FormHandler/Manual/Intro.pod

The example given also appears to be identical.  This caused me some confusion on the first readthrough.

delete description of feature that was described a little earlier

---

lib/HTML/FormHandler/TraitFor/Types.pm
t/fields/select.t

021fd3b failed to dereference an array sufficiently.  The tests I wrote
for it and d02fe16 did not check everything worked all the way through
to rendering.  This commit addresses those inadequacies.

Fix options processing and test rendering

---

dist.ini
lib/HTML/FormHandler/Render/RepeatableJs.pm

The latter handles more backends (i.e. Cpanel::JSON::XS) and has
installation logic to ensure the best possible backend is installed to
suit the local environment, at a fixed version.

switch from JSON.pm to JSON::MaybeXS

---

Changes
lib/HTML/FormHandler/Field/Text.pm

This means that any defined transform or deflation could not alter the
value to something that would validate.

Text validations were being tested in input, not value!

---

lib/HTML/FormHandler/Field/Date.pm
t/fields/dates.t

This allows the boundaries to be recalculated every time the form is
processed, rather than once up front when the form is declared -- the
difference is relevant for long-running code.

accept coderefs for date_start, date_end in Date field

---

lib/HTML/FormHandler/Field.pm

In HTML::FormHandler::Field build_validate_method looks for a method "validate_$name" even if the field name is 'model', so validate_model is called when validating field. The PR avoids this behaviour.

fix: validate_model should not be called to validate a field named 'model'

---

lib/HTML/FormHandler/BuildFields.pm

perldoc perlsyn:
> The behaviour of a `my`, `state`, or `our` modified with a statement modifier conditional or loop construct (for example, `my $x if ...` ) is **undefined**.

avoid conditional variable declaration

---

dist.ini
lib/HTML/FormHandler/Field/Repeatable.pm

It's a non core module, the use of which is so minimal that it doesn't really buy us anything. So just drop it and reduce the weight :-)

Drop dependency on aliased

---

lib/HTML/FormHandler/Widget/Block.pm

Simple fix for #149 
I created #149 before I thought of just pressing edit and fixing it, so feel free to close it.

Create `render_start` and `render_end` for Blocks
